[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove any redirects that might be causing issues
# [[redirects]]
#  from = "/*"
#  to = "/index.html"
#  status = 200